markdown: rdiscount
permalink: /:title/
url: http://linux323.tk
name: Sn0rt's Blog
author: Sn0rt
qq: 1175460346
email: Sn0rt@abc.shop.edu.cn
duoshuo: Dante
beian: 
cnzz: 
weibo: 
github: Sn0rt
highlighter: pygments
markdown: redcarpet
safe: true
paginate: 20
about: " 一切有为法，如梦幻泡影，如露亦如电，应作如是观"
